services:
  mongodb:
    image: mongo:7.0.1
    ports:
      - "27017:27017"

  backend-service:
    build: ./backend
    image: aryasingh1234/amazone_clone:backend-v1
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb

  frontend:
    build: ./frontend
    image: aryasingh1234/amazone_clone:frontend-v1
    ports:
      - "3000:3000"
    depends_on:
      - backend-service