apiVersion: v1
kind: Secret
metadata:
  name: amazon-secrets
  namespace: amazon-clone
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_PASSWORD: "admin"
  SECRET_KEY: "django-insecure-prod-key-change-me-in-production-12345"
  JWT_SECRET: "super-secret-jwt-key-amazon-clone-2026"
