apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-config
  namespace: amazon-clone
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,your-domain.com"
  DB_NAME: "amazon_clone"
  DB_USER: "root"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  VITE_API_URL: "http://your-domain.com/api"
